language: csharp  
sudo: required  
dist: trusty
# OS X 10.12
osx_image: xcode9.2
env:  
  - CLI_VERSION=latest
mono:  
  - 5.10.0
dotnet:
  - 1.1.5  
  - 2.1.400
os:
  - osx
  - linux
branches:  
  only:
    - master
    - /.*/
before_script:
- chmod +x ./build.sh
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install nuget; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo apt install nuget; fi
script:  
  - ./build.sh